version: "3"

server:
  command: "php -c app.prod.ini bin/server"

http:
  address: "${SERVER_BIND:-0.0.0.0}:${SERVER_PORT:-80}"
  max_request_size: 64
  middleware:
    - static
  pool:
    supervisor:
      exec_ttl: 15s
      max_worker_memory: 128
  static:
    dir: "./public"
    calculate_etag: true
    weak: false
    response:
      "Cache-Control": "public, max-age=0, must-revalidate"
      "X-Content-Type-Options": "nosniff"

status:
  address: 127.0.0.1:2114

logs:
  mode: production
  level: error
  encoding: json
  file_logger_options:
    log_output: "data/log/roadrunner.log"
